# Use root/example user/password credentials
version: "3"

services:
  web:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./app:/app
  php:
    build:
      context: .
      dockerfile: PHP.Dockerfile
    volumes:
      - ./app:/app

  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: "u04_todo_app"
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3300:3300

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080

volumes:
  mysql-data: {}
